### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by VenomFate-619** [neerajsurjaye/SPRT#1]
I followed the steps given in the readme but was unable to start.

![image](https://github.com/neerajsurjaye/sprt/assets/67755128/c8eb0882-3277-4099-a5bd-b1b7b834a228)

![image](https://github.com/neerajsurjaye/sprt/assets/67755128/bc783a4c-f7ec-4dd5-968e-685e614282fa)

**Comment by neerajsurjaye** [comment]
Fixed the issue. 
The command given in readme.md was wrong.
Now fixed. :)
